project_id = "jnspiqnlwbsobqctmfnk"

[functions.generate-training-plan]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.extract-nutrition-label]
verify_jwt = true

[functions.facts]
verify_jwt = true

[functions.assign-daily-facts]
verify_jwt = false

[functions.generate-fact-library]
verify_jwt = false
